services:
  web1:
    build: .
    volumes:
      - ./visits.json:/app/visits.json
    ports:
      - "5002:5000"

  web2:
    build: .
    volumes:
      - ./visits.json:/app/visits.json
    ports:
      - "5001:5000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "5000:5000"


