services:
  db:
    image: postgres:latest

    restart: always
    environment:
      POSTGRES_USER: doaa
      POSTGRES_PASSWORD: doaa
      POSTGRES_DB: task_list


  web:
    image: firstimage
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: task_list
      DB_NAME: doaa
      DB_USER: doaa
      DB_PASS: doaa


